---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pgupgrade
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: pgupgrade
  targetNamespace: default

